name: dockerbuild
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '38 14 * * 0'
  
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    env:
      PROJECT: "gcfr-352018"
    steps:
    - uses: actions/checkout@v3

#    - name: Authenticate to Google Cloud
#      uses: google-github-actions/auth@v0
#      with:
#        credentials_json: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}
#
#    - name: Configure Docker
#      run: gcloud auth configure-docker --quiet

    - name: calculate image-tag
      run: |
        branchName="$(git rev-parse --abbrev-ref HEAD)"
        commitId="$(git rev-parse --short HEAD)"
        repoName="$(basename `git rev-parse --show-toplevel`)"

        if [[ ${branchName} == main ]] ; then
          prefix=M
        else
          prefix=F-$(echo $branchName | cut -f 2 -d/)
        fi

        tag="$repoName:$prefix-$(date '+%Y%m%d')-$commitId"
        echo "TAG=$(echo $tag)" >> $GITHUB_ENV

    - name: Build
      run: docker build . -t eu.gcr.io/${{ env.PROJECT }}/${{ env.TAG }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
        image-ref: 'eu.gcr.io/${{ env.PROJECT }}/${{ env.TAG }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

#    - name: Scan
#      uses: sysdiglabs/scan-action@v3.0.1
#      with:
#        image-tag: eu.gcr.io/${{ env.PROJECT }}/${{ env.TAG }}
#        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
#        sysdig-secure-url: https://eu1.app.sysdig.com/
#        input-type: docker-daemon
#        run-as-user: root
#        input-path: /run/docker.sock
        
#    - name: Push
#      run: docker push eu.gcr.io/${{ env.PROJECT }}/${{ env.TAG }}
